### ISSUE TITLE
Level Select Buttons Hover Sound Fix

### ISSUE THREAD

**Issue by jpark052** [CobeyH/Leora#251]
When you hover buttons in level select screen fast, it skips some sound effect. Make it so that when the user hovers over to another button while "Hover sound" is playing, stop that sound and play new "Hover sound"

**Comment by CobeyH** [comment]
Make sure to merge the pull request with the volume changes before you work on this. It has significant changes to the audio manager script.

**Comment by jpark052** [comment]
> 

Thanks for the heads up!
